# Generated by Django 4.2.2 on 2023-10-04 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
